import { Inter } from 'next/font/google';
import ColorMix from '../../components/colorMix/ColorMix';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Color Mix Fun',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return <ColorMix>{children}</ColorMix>;
}
